/**
 * @file tkl_bluetooth.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

#include "tkl_bluetooth.h"
#include "tuya_cloud_types.h"
#include "tuya_error_code.h"
#include <stdio.h>

//#include "tuya_bluez_api.h"
#include "tal_log.h"

// Forward declarations for functions defined in bt_dbus_api.c
void bluez_inc_init(TKL_BLE_GAP_EVT_FUNC_CB gap_evt_cb, TKL_BLE_GATT_EVT_FUNC_CB gatt_evt_cb);
void bluez_inc_deinit(void);
void bluez_inc_start_adv(void);
void bluez_inc_disconnect(void);
void bluez_inc_add_gatt(TKL_BLE_GATTS_PARAMS_T *p_service);
int bluez_inc_gatt_value_notify(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length);

// Forward declarations for functions defined in bt_hci_adv_api.c
int tuya_hci_le_set_adv_enable(bool enable);
int tuya_hci_le_set_adv_params(uint16_t min_interval, uint16_t max_interval, uint8_t advtype);
int tuya_hci_le_set_adv_data(uint8_t *p_data, uint8_t length);
int tuya_hci_le_set_scan_rsp_data(uint8_t *p_data, uint8_t length);

static TKL_BLE_GAP_EVT_FUNC_CB  __gap_evt_cb  = NULL;
static TKL_BLE_GATT_EVT_FUNC_CB __gatt_evt_cb = NULL;

static uint16_t tuya_conn_handle ={0};

void tuya_gap_init_callback()
{
    TKL_BLE_GAP_PARAMS_EVT_T event;

    memset(&event, 0, SIZEOF(TKL_BLE_GAP_PARAMS_EVT_T));

    event.result = 0;
    event.type = TKL_BLE_EVT_STACK_INIT;
    event.conn_handle            = tuya_conn_handle;//BLE_CONN_HANDLE;
                                                    //
    event.gap_event.connect.role = TKL_BLE_ROLE_SERVER;

    if (__gap_evt_cb) {
        __gap_evt_cb(&event);
    }
}

/**
 * @brief   Function for initializing the ble stack
 * @param   role                Indicate the role for ble stack.
 *                              role = 1: ble peripheral    @TKL_BLE_ROLE_SERVER
 *                              role = 2: ble central       @TKL_BLE_ROLE_CLIENT
 * @return  SUCCESS             Initialized successfully.
 *          ERROR
 * */
OPERATE_RET tkl_ble_stack_init(uint8_t role)
{
    printf("tkl_ble_stack_init, role=%d",role);
    bluez_inc_init(__gap_evt_cb, __gatt_evt_cb);

    tuya_gap_init_callback();
    return OPRT_OK;
}

/**
 * @brief   Function for de-initializing the ble stack features
 * @param   role                 Indicate the role for ble stack.
 *                               role = 1: ble peripheral
 *                               role = 2: ble central
 * @return  SUCCESS             Deinitialized successfully.
 *          ERROR
 * */
OPERATE_RET tkl_ble_stack_deinit(uint8_t role)
{
    printf("tkl_ble_stack_deinit, role=%d",role);
    bluez_inc_deinit();
    return OPRT_OK;
}

/**
 * @brief   Function for getting the GATT Link-Support.
 * @param   p_link              return gatt link                 
 * @return  SUCCESS             Support Gatt Link
 *          ERROR               Only Beacon or Mesh Beacon, Not Support Gatt Link.
 * */
OPERATE_RET tkl_ble_stack_gatt_link(uint16_t *p_link)
{
    printf("tkl_ble_stack_gatt_link");   
}

/**
 * @brief   Register GAP Event Callback
 * @param   TKL_BLE_GAP_EVT_FUNC_CB Refer to @TKL_BLE_GAP_EVT_FUNC_CB
 * @return  SUCCESS         Register successfully.
 *          ERROR
 * */
OPERATE_RET tkl_ble_gap_callback_register(const TKL_BLE_GAP_EVT_FUNC_CB gap_evt)
{
    printf("tkl_ble_gap_callback_register\n");      
    __gap_evt_cb = gap_evt;
    return OPRT_OK;
}

/**
 * @brief   Register GATT Event Callback
 * @param   TKL_BLE_GATT_EVT_FUNC_CB Refer to @TKL_BLE_GATT_EVT_FUNC_CB
 * @return  SUCCESS         Register successfully.
 *          ERROR
 * */
OPERATE_RET tkl_ble_gatt_callback_register(const TKL_BLE_GATT_EVT_FUNC_CB gatt_evt)
{
    printf("tkl_ble_gatt_callback_register\n");
    __gatt_evt_cb = gatt_evt;
    return OPRT_OK;
}

/******************************************************************************************************************************/
/** @brief Define All GAP Interface
 */
/**
 * @brief   Set the local Bluetooth identity address.
 *          The local Bluetooth identity address is the address that identifies this device to other peers.
 *          The address type must be either @ref TKL_BLE_GAP_ADDR_TYPE_PUBLIC or @ref TKL_BLE_GAP_ADDR_TYPE_RANDOM.
 * @param   [in] p_peer_addr:   pointer to local address parameters 
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_addr_set(TKL_BLE_GAP_ADDR_T const *p_peer_addr)
{
    printf("tkl_ble_gap_addr_set");
}
 
/**
 * @brief   Get the local Bluetooth identity address.
 * @param   [out] p_peer_addr:  pointer to local address
 * @return  SUCCESS             Set Address successfully.
 *          ERROR
 * */
OPERATE_RET tkl_ble_gap_address_get(TKL_BLE_GAP_ADDR_T *p_peer_addr)
{
    printf("tkl_ble_gap_address_get");
}
 
/**
 * @brief   Start advertising
 * @param   [in] p_adv_params : pointer to advertising parameters 
 * @return  SUCCESS
 *  ERROR
 * */ 
static uint16_t sg_min_adv_interval, sg_max_adv_interval; 
void binc_start_adv_success_cb(void) {
    tuya_hci_le_set_adv_enable(0);
    tuya_hci_le_set_adv_params(sg_min_adv_interval, sg_max_adv_interval, 0);
    tuya_hci_le_set_adv_enable(1);
}
OPERATE_RET tkl_ble_gap_adv_start(TKL_BLE_GAP_ADV_PARAMS_T const *p_adv_params)
{
	printf("tkl_ble_gap_adv_start\n");
    printf("tkl_ble_gap_adv_start:interval(%d,%d),type:%d", p_adv_params->adv_interval_min, p_adv_params->adv_interval_max, p_adv_params->adv_type);
    #if 0
    0x00	Public Device Address (公共地址，即 hciconfig 显示的地址)
    0x01	Random Device Address (随机地址)
    0x02	Resolvable Private Address (使用公共地址)
    0x03	Resolvable Private Address (使用随机地址)
    如果这个字段没有被显式设置为 0x00，它可能会默认为一个无效值（例如 0x00 但由于某些实现差异导致无效），或者控制器可能预期使用随机地址但您的程序没有设置。
    #endif

    // 1）需要启动 bluetoothd 的 adv 否则连接不上（因为 bluetoothd 在连接时会检查）
    // 2）hci 设置广播和响应包时无关广播是否使能，但是在设置广播间隔时一定要先关再开
    // 3）bluetoothd 的 adv 初始化包括广播间隔的设置，属于异步的，因此需要等其完全执行完再 hci 相关的 adv 配置，否则广播间隔会被覆盖
    //     - 实践发现加 delay 不行    // usleep(100 * 1000); // 暂停 100,000 微秒 = 100 毫秒
    //     - 在 binc/adapter.c 中找到广播执行成功的回调函数
    sg_min_adv_interval = p_adv_params->adv_interval_min;
    sg_max_adv_interval = p_adv_params->adv_interval_max;
    bluez_inc_start_adv();

    return OPRT_OK;
}

/**
 * @brief   Stop advertising
 * @param   void
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_adv_stop(void)
{
    printf("tkl_ble_gap_adv_stop\n");
    tuya_hci_le_set_adv_enable(0);
   	return OPRT_OK;
}

/**
 * @brief   Setting advertising data
 * @param   [in] p_adv:         Data to be used in advertisement packets, and include adv data len
 *          [in] p_scan_rsp:    Data to be used in advertisement respond packets, and include rsp data len
 * @Note    Please Check p_adv and p_scan_rsp, if data->p_data == NULL or data->length == 0, we will not update these values.
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_adv_rsp_data_set(TKL_BLE_DATA_T const *p_adv, TKL_BLE_DATA_T const *p_scan_rsp)
{
    printf("tkl_ble_gap_adv_rsp_data_set\n"); 
#if 0 
    if (p_adv != NULL && p_adv->p_data != NULL && p_adv->length > 0) {
        printf("------------------ Advertising Data ------------------\n");
        printf("Advertising Data\n", p_adv->p_data, p_adv->length);
    } else {
        printf("------------------ Advertising Data ------------------\n");
        printf("Advertising data is NULL or empty.\n");
    }

    if (p_scan_rsp != NULL && p_scan_rsp->p_data != NULL && p_scan_rsp->length > 0) {
        printf("----------------- Scan Response Data -----------------\n");
        printf("Scan Response Data\n", p_scan_rsp->p_data, p_scan_rsp->length);
    } else {
        printf("----------------- Scan Response Data -----------------\n");
        printf("Scan response data is NULL or empty.\n");
    }

    bluez_inc_update_adv(p_adv, p_scan_rsp);
    //bluez_inc_set_adv();
#else
    tuya_hci_le_set_adv_data(p_adv->p_data, p_adv->length);
    tuya_hci_le_set_scan_rsp_data(p_scan_rsp->p_data, p_scan_rsp->length);
#endif
    return OPRT_OK;
}

/**
 * @brief   Update advertising data
 * @param   [in] p_adv: Data    to be used in advertisement packets, and include adv data len
 *          [in] p_scan_rsp:    Data to be used in advertisement respond packets, and include rsp data len
 * @Note    Please Check p_adv and p_scan_rsp, if data->p_data == NULL or data->length == 0, we will not update these values.
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_adv_rsp_data_update(TKL_BLE_DATA_T const *p_adv, TKL_BLE_DATA_T const *p_scan_rsp)
{
    printf("tkl_ble_gap_adv_rsp_data_update\n");
#if 0
    if (p_adv != NULL && p_adv->p_data != NULL && p_adv->length > 0) {
        printf("------------------ Advertising Data ------------------\n");
        printf("Advertising Data\n", p_adv->p_data, p_adv->length);
    } else {
        printf("------------------ Advertising Data ------------------\n");
        printf("Advertising data is NULL or empty.\n");
    }

    if (p_scan_rsp != NULL && p_scan_rsp->p_data != NULL && p_scan_rsp->length > 0) {
        printf("----------------- Scan Response Data -----------------\n");
        printf("Scan Response Data\n", p_scan_rsp->p_data, p_scan_rsp->length);
    } else {
        printf("----------------- Scan Response Data -----------------\n");
        printf("Scan response data is NULL or empty.\n");
    }

    return OPRT_OK;
#else
    tuya_hci_le_set_adv_data(p_adv->p_data, p_adv->length);
    tuya_hci_le_set_scan_rsp_data(p_scan_rsp->p_data, p_scan_rsp->length);
    return OPRT_OK;
#endif
}

/**
 * @brief   Start scanning
 * @param   [in] scan_param:    scan parameters including interval, windows
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_scan_start(TKL_BLE_GAP_SCAN_PARAMS_T const *p_scan_params)
{
    printf("tkl_ble_gap_scan_start");      
}

/**
 * @brief   Stop scanning
 * @param   void
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_scan_stop(void)
{
    printf("tkl_ble_gap_scan_stop");         
}

/**
 * @brief   Start connecting one peer
 * @param   [in] p_peer_addr:   include address and address type
 *          [in] p_scan_params: scan parameters
 *          [in] p_conn_params: connection  parameters
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_connect(TKL_BLE_GAP_ADDR_T const *p_peer_addr, TKL_BLE_GAP_SCAN_PARAMS_T const *p_scan_params, TKL_BLE_GAP_CONN_PARAMS_T const *p_conn_params)
{
    printf("tkl_ble_gap_connect");            
}

/**
 * @brief   Disconnect from peer
 * @param   [in] conn_handle:   the connection handle
 *          [in] hci_reason:    terminate reason
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_disconnect(uint16_t conn_handle, uint8_t hci_reason)
{
    printf("tkl_ble_gap_disconnect");               
    bluez_inc_disconnect();
    return OPRT_OK;
}

/**
 * @brief   Start to update connection parameters
 * @param   [in] conn_handle:   connection handle
 *          [in] p_conn_params: connection  parameters
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_gap_conn_param_update(uint16_t conn_handle, TKL_BLE_GAP_CONN_PARAMS_T const *p_conn_params)
{
    printf("tkl_ble_gap_conn_param_update");
}

/**
 * @brief   Set the radio's transmit power.
 * @param   [in] role:          0: Advertising Tx Power; 1: Scan Tx Power; 2: Connection Power
 *          [in] tx_power:      tx power:This value will be magnified 10 times. 
 *                              If the tx_power value is -75, the real power is -7.5dB.(or 40 = 4dB)
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gap_tx_power_set(uint8_t role, int tx_power)
{
    printf("tkl_ble_gap_tx_power_set");
}

/**
 * @brief   Get the received signal strength for the last connection event.
 * @param   [in]conn_handle:    connection handle
 * @return  SUCCESS             Successfully read the RSSI.
 *          ERROR               No sample is available.
 * */
OPERATE_RET tkl_ble_gap_rssi_get(uint16_t conn_handle)
{
    printf("tkl_ble_gap_rssi_get");
}

/**
 * @brief   Set the GAP Name For Bluetooth
 * @param   [in]p_name:         GAP Name String
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_gap_name_set(char *p_name)
{
    printf("tkl_ble_gap_name_set");
}

/**
 * @brief   Add Ble Gatt Service
 * @param   [in] p_service: define the ble service
 *
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gatts_service_add(TKL_BLE_GATTS_PARAMS_T *p_service)
{
#if 1  // LOG
    // 有些 wifi+ble 应用先调用了这个再调用初始化，
    // 导致失败，这里直接也调用下协议栈初始化，同时该函数做了防重复初始化
    bluez_inc_init(__gap_evt_cb, __gatt_evt_cb);
    printf("tkl_ble_gatts_service_add\n");
    printf("svc_num=%d\n", p_service->svc_num);

    // 遍历每一个服务
    for (int i = 0; i < p_service->svc_num; i++) {
        TKL_BLE_SERVICE_PARAMS_T *p_svc = &(p_service->p_service[i]);

        printf("-------------------- Service[%d] --------------------\n", i);
        printf("handle = 0x%x\n", p_svc->handle);

        // 根据 UUID 类型打印服务 UUID
        switch (p_svc->svc_uuid.uuid_type) {
            case TKL_BLE_UUID_TYPE_16:
                printf("svc_uuid = 0x%04x (16-bit)\n", p_svc->svc_uuid.uuid.uuid16);
                break;
            case TKL_BLE_UUID_TYPE_32:
                printf("svc_uuid = 0x%08x (32-bit)\n", p_svc->svc_uuid.uuid.uuid32);
                break;
            case TKL_BLE_UUID_TYPE_128:
                printf("svc_uuid = %02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x (128-bit LE)\n",
                            p_svc->svc_uuid.uuid.uuid128[15], p_svc->svc_uuid.uuid.uuid128[14], p_svc->svc_uuid.uuid.uuid128[13], p_svc->svc_uuid.uuid.uuid128[12],
                            p_svc->svc_uuid.uuid.uuid128[11], p_svc->svc_uuid.uuid.uuid128[10],
                            p_svc->svc_uuid.uuid.uuid128[9], p_svc->svc_uuid.uuid.uuid128[8],
                            p_svc->svc_uuid.uuid.uuid128[7], p_svc->svc_uuid.uuid.uuid128[6],
                            p_svc->svc_uuid.uuid.uuid128[5], p_svc->svc_uuid.uuid.uuid128[4], p_svc->svc_uuid.uuid.uuid128[3], p_svc->svc_uuid.uuid.uuid128[2], p_svc->svc_uuid.uuid.uuid128[1], p_svc->svc_uuid.uuid.uuid128[0]);
                break;
            default:
                printf("svc_uuid = Unknown UUID Type\n");
                break;
        }

        printf("type = 0x%x\n", p_svc->type);
        printf("char_num = %d\n", p_svc->char_num);

        // 遍历当前服务下的每一个特征值
        for (int j = 0; j < p_svc->char_num; j++) {
            TKL_BLE_CHAR_PARAMS_T *p_char = &(p_svc->p_char[j]);
            
            printf("    -------------------- Char[%d] --------------------\n", j);
            printf("    handle = 0x%x\n", p_char->handle);
            
            // 根据 UUID 类型打印特征值 UUID
            switch (p_char->char_uuid.uuid_type) {
                case TKL_BLE_UUID_TYPE_16:
                    printf("    char_uuid = 0x%04x (16-bit)\n", p_char->char_uuid.uuid.uuid16);
                    break;
                case TKL_BLE_UUID_TYPE_32:
                    printf("    char_uuid = 0x%08x (32-bit)", p_char->char_uuid.uuid.uuid32);
                    break;
                case TKL_BLE_UUID_TYPE_128:
                    printf("    char_uuid = %02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x (128-bit LE)\n",
                                p_char->char_uuid.uuid.uuid128[15], p_char->char_uuid.uuid.uuid128[14], p_char->char_uuid.uuid.uuid128[13], p_char->char_uuid.uuid.uuid128[12],
                                p_char->char_uuid.uuid.uuid128[11], p_char->char_uuid.uuid.uuid128[10],
                                p_char->char_uuid.uuid.uuid128[9], p_char->char_uuid.uuid.uuid128[8],
                                p_char->char_uuid.uuid.uuid128[7], p_char->char_uuid.uuid.uuid128[6],
                                p_char->char_uuid.uuid.uuid128[5], p_char->char_uuid.uuid.uuid128[4], p_char->char_uuid.uuid.uuid128[3], p_char->char_uuid.uuid.uuid128[2], p_char->char_uuid.uuid.uuid128[1], p_char->char_uuid.uuid.uuid128[0]);
                    break;
                default:
                    printf("    char_uuid = Unknown UUID Type\n");
                    break;
            }
            printf("    property = 0x%x\n", p_char->property);
            printf("    permission = 0x%x\n", p_char->permission);
            printf("    value_len = %d\n", p_char->value_len);
        }
    }
#endif
    bluez_inc_add_gatt(p_service);
    return OPRT_OK;
}

/**
 * @brief   [Optional] Indicates a change in attribute assignment to all subscribed peers(Specify conn_handle).
 * 
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] start_handle   The start of the affected handle range.
 * @param   [in] end_handle     The end of the affected handle range.
 * 
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gatts_service_change(uint16_t conn_handle, uint16_t start_handle, uint16_t end_handle)
{
    printf("tkl_ble_gatts_service_change");
}

/**
 * @brief   Set the value of a given attribute. After Config Tuya Read-Char, we can update read-value at any time.
 * @param   [in] conn_handle    Connection handle.
 *          [in] char_handle    Attribute handle.
 *          [in,out] p_value    Attribute value information.
 * @return  SUCCESS
 *          ERROR
 *
 * @note Values other than system attributes can be set at any time, regardless of whether any active connections exist. 
 * */ 
OPERATE_RET tkl_ble_gatts_value_set(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length)
{
    printf("tkl_ble_gatts_value_set");
}

/**
 * @brief   Get the value of a given attribute.
 * @param   [in] conn_handle    Connection handle. Ignored if the value does not belong to a system attribute.
 * @param   [in] char_handle    Attribute handle.
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gatts_value_get(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length)
{
    printf("tkl_ble_gatts_value_get");
}

/**
 * @brief   Notify an attribute value.
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] char_handle    Attribute handle.
 *          [in] p_data         Notify Values
 *          [in] length         Value Length
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gatts_value_notify(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length)
{
    printf("tkl_ble_gatts_value_notify");
    return bluez_inc_gatt_value_notify(conn_handle, char_handle, p_data, length);
}

/**
 * @brief   Indicate an attribute value.
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] char_handle    Attribute handle.
 *          [in] p_data         Notify Values
 *          [in] length         Value Length
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gatts_value_indicate(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length)
{
   printf("tkl_ble_gatts_value_indicate"); 
}

/**
 * @brief   Reply to an ATT_MTU exchange request by sending an Exchange MTU Response to the client.
 * @param   [in] conn_handle    Connection handle.
 *          [in] server_rx_mtu  mtu size.
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gatts_exchange_mtu_reply(uint16_t conn_handle, uint16_t server_rx_mtu)
{
    printf("tkl_ble_gatts_exchange_mtu_reply"); 
}

/******************************************************************************************************************************/
/** @brief Define All Gatt Client Interface, Refer to current ble gw and ble stack.
 *
 *  Notes: notice the handle will be the one of signed point.
 *  Discovery Operations belongs to GAP Interface, But declear here, because it will be used for the gatt client.
 */
 
/**
 * @brief   [Ble Central] Will Discovery All Service
 * @param   [in] conn_handle    Connection handle.
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gattc_all_service_discovery(uint16_t conn_handle)
{
    printf("tkl_ble_gattc_all_service_discovery"); 
}

/**
 * @brief   [Ble Central] Will Discovery All Characteristic
 * @param   [in] conn_handle    Connection handle.
 *          [in] start_handle   Handle of start
 *          [in] end_handle     Handle of End
 * @return  SUCCESS
 *          ERROR
 * @Note:   For Tuya Service, it may contains more optional service, it is more better to find all Characteristic 
 *          instead of find specific uuid.
 * */  
OPERATE_RET tkl_ble_gattc_all_char_discovery(uint16_t conn_handle, uint16_t start_handle, uint16_t end_handle)
{
    printf("tkl_ble_gattc_all_char_discovery");
}

/**
 * @brief   [Ble Central] Will Discovery All Descriptor of Characteristic
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] conn_handle    Connection handle.
 *          [in] start_handle   Handle of start
 *          [in] end_handle     Handle of End
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gattc_char_desc_discovery(uint16_t conn_handle, uint16_t start_handle, uint16_t end_handle)
{
    printf("tkl_ble_gattc_char_desc_discovery"); 
}

/**
 * @brief   [Ble Central] Write Data without Response
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] char_handle    Attribute handle.
 *          [in] p_data         Write Values
 *          [in] length         Value Length
 * @return  SUCCESS
 *          ERROR
 * */ 
OPERATE_RET tkl_ble_gattc_write_without_rsp(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length)
{
    printf("tkl_ble_gattc_write_without_rsp") ;
}

/**
 * @brief   [Ble Central] Write Data with response
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] char_handle    Attribute handle.
 *          [in] p_data         Write Values
 *          [in] length         Value Length
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_gattc_write(uint16_t conn_handle, uint16_t char_handle, uint8_t *p_data, uint16_t length)
{
    printf("tkl_ble_gattc_write");
}

/**
 * @brief   [Ble Central] Read Data
 * @param   [in] conn_handle    Connection handle.
 * @param   [in] char_handle    Attribute handle.
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_gattc_read(uint16_t conn_handle, uint16_t char_handle)
{
    printf("tkl_ble_gattc_read"); 
}

/**
 * @brief   Start an ATT_MTU exchange by sending an Exchange MTU Request to the server.
 * @param   [in] conn_handle    Connection handle.
 *          [in] client_rx_mtu  mtu size.
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_gattc_exchange_mtu_request(uint16_t conn_handle, uint16_t client_rx_mtu)
{
    printf("tkl_ble_gattc_exchange_mtu_request");
}

/**
 * @brief   [Special Command Control] Base on Bluetooth, We can do some special commands for exchanging some informations.
 * @param   [in] opcode         Operations Opcode.
 *          [in] user_data      Post Some Special Commands Data.
 *          [in] data_len       User's Data Length.
 * @note    For Operations Codes, we can do anythings after exchange from TAL Application
 *          And We define some Opcodes as below for reference.
 *          For Bluetooth NCP Module: Mask=0x01, Code ID: 0x00~0xff. Opcode = ((0x01 << 8) & Code ID)
 *          eg:     0x0100: Special Vendor Module Init
 *                  0x0101: Special Vendor Module Deinit
 *                  0x0102: Special Vendor Module Reset
 *                  0x0103: Special Vendor Module Check Exist: Return OPRT_OK or OPRT_NOT_FOUND ..
 *                  0x0104: Specail Vendor Module Version Get.
 *                  0x0105: Specail Vendor Module Version Set.
 *                  0x0106: Specail Vendor Module Version Update.
 *                  0x0107: Specail Vendor Module Scan Switch.
 *                  0x0108: Specail Vendor Module Scan Stop.
 *                  0x0109: Specail Vendor Module Auth Check.
 *                  0x0110: Specail Vendor Module Auth Erase.
 *
 *  * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_vendor_command_control(uint16_t opcode, void *user_data, uint16_t data_len)
{
    printf("tkl_ble_vendor_command_control");
}

/**
 * @brief set ble mode, used in wifi ble coexist mode
 * 
 * @param[in]       enable     enbale mode
 * @param[in]       mode       the ble mode
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_ble_set_mode(const BOOL_T enable, const uint8_t mode)
{
    printf("tkl_ble_set_mode");
}

/**
 * @brief   Set country code, different country codes have different TX powers.
 * @param   [in] country_code    Country code.
 *                              COUNTRY_CODE_CN     0
 *                              COUNTRY_CODE_US     1
 *                              COUNTRY_CODE_JP     2
 *                              COUNTRY_CODE_EU     3
 *                              COUNTRY_CODE_JP1    4
 * @return  SUCCESS
 *          ERROR
 * */
OPERATE_RET tkl_ble_gap_country_set(uint8_t country_code)
{
    printf("tkl_ble_gap_country_set");
}

